BEGIN;

UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'fixed-reader-checks' AND key = 'startTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'fixed-reader-checks' AND key = 'endTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'salting-and-tumbling' AND key = 'startTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'salting-and-tumbling' AND key = 'finishTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'bleeding-and-salting' AND key = 'bleedingStartTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'bleeding-and-salting' AND key = 'bleedingFinishTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'bleeding-and-salting' AND key = 'saltingStartTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'bleeding-and-salting' AND key = 'saltingFinishTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'washing-control-sheet' AND key = 'timeStarted';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'scrubbing-check-supervisor' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'scrubbing-checklist-qc' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'precooking-check-sheet' AND key = 'precookingStartTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'can-packing-control-sheet' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'can-filling-and-printing' AND key = 'startTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'printing-control-sheet' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'cans-produced' AND key = 'timeTrolleyIn';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'retorting-control-sheet' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'retorting-control-sheet' AND key = 'timeTrolleyIn';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'retorting-control-sheet' AND key = 'timeTrolleyOut';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'retort-inspection-report' AND key = 'timeTrolleyIn';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'dry-cooking' AND key = 'startTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'dry-cooking' AND key = 'timeOut';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'dry-stock-transfers' AND key = 'timeOfTransfer';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'live-pack-checklist' AND key = 'startTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'live-pack-checklist' AND key = 'timeFinishedPacking';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'glass-breakage-clearance-certificate' AND key = 'timeOfBreakage';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'glass-breakage-clearance-certificate' AND key = 'timeOfRestart';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'plaster-dressing-inspection' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'plaster-dressing-inspection' AND key = 'breakTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'plaster-dressing-inspection' AND key = 'lunchTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'plaster-dressing-inspection' AND key = 'knockOffTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'first-aid-checklist-record' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'first-aid-checklist-record' AND key = 'breakTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'chiller-batch-control' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'dry-chiller-batch-control' AND key = 'time';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'maintenance-job-card' AND key = 'timeStarted';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'maintenance-job-card' AND key = 'timeFinished';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'daily-waste-removal' AND key = 'timeOfCollection';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'boiler-inspection-report' AND key = 'timeBoilerStarted';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'boiler-inspection-report' AND key = 'timeBoilerTurnedOff';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'lha-water-monitoring' AND key = 'timeOfCheck';
UPDATE "RecordFieldDef" SET type = 'datetime' WHERE "recordKey" = 'withdrawal-mock-recall-record' AND key = 'dateTimeStarted';
UPDATE "RecordFieldDef" SET type = 'datetime' WHERE "recordKey" = 'withdrawal-mock-recall-record' AND key = 'dateTimeFinished';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'traceability' AND key = 'startTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'traceability' AND key = 'finishTime';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'emergency-evacuation-attendance-register' AND key = 'timeStarted';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'emergency-evacuation-attendance-register' AND key = 'timeEnded';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'handling-of-emergencies-and-incidences' AND key = 'timeEvacuating';
UPDATE "RecordFieldDef" SET type = 'time' WHERE "recordKey" = 'handling-of-emergencies-and-incidences' AND key = 'timeReturning';

UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'fixed-reader-checks';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'salting-and-tumbling';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'bleeding-and-salting';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'washing-control-sheet';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'scrubbing-check-supervisor';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'scrubbing-checklist-qc';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'precooking-check-sheet';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'can-packing-control-sheet';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'can-filling-and-printing';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'printing-control-sheet';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'cans-produced';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'retorting-control-sheet';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'retort-inspection-report';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'dry-cooking';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'dry-stock-transfers';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'live-pack-checklist';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'glass-breakage-clearance-certificate';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'plaster-dressing-inspection';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'first-aid-checklist-record';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'chiller-batch-control';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'dry-chiller-batch-control';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'maintenance-job-card';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'daily-waste-removal';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'boiler-inspection-report';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'lha-water-monitoring';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'withdrawal-mock-recall-record';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'traceability';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'emergency-evacuation-attendance-register';
UPDATE "RecordDefinition" SET version = version + 1, "updatedAt" = now() WHERE "recordKey" = 'handling-of-emergencies-and-incidences';

COMMIT;
