-- Dry Export Pack Front Page: rebuild from the paper form. Replaces THIS record's definition only.
-- Removes the old drifted definition (extra fields, sign-off fields, TEST field). Safe to re-run.
BEGIN;
DELETE FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page';
DELETE FROM "RecordSectionDef" WHERE "recordKey"='dry-export-pack-front-page';
DELETE FROM "RecordAutofillDef" WHERE "recordKey"='dry-export-pack-front-page';
UPDATE "RecordDefinition" SET "engine"='form-record',"mount"='#frRoot',"pageFile"='Dry-Export-Pack-Front-Page-dry-export-pack-front-page.html',"docCode"='Dry Export Pack Front Page',"title"='Dry Export Pack Front Page',"docRevisionStart"=1,"jobInfoGroup"=NULL,"clientHook"=NULL,"primaryBatchField"=NULL,"extraBatchFields"=ARRAY[]::text[],"extraJson"='{"listColumns": ["exportInvoiceNo", "packingDate"]}'::jsonb,"version"="version"+1,"updatedAt"=now() WHERE "recordKey"='dry-export-pack-front-page';
INSERT INTO "RecordSectionDef" ("id","recordKey","title","kind","position","extraJson") VALUES ('dep2_sec_0','dry-export-pack-front-page','Shipment details','fields',0,NULL);
INSERT INTO "RecordSectionDef" ("id","recordKey","title","kind","position","extraJson") VALUES ('dep2_sec_1','dry-export-pack-front-page','Attachments checklist','fields',1,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_0','dry-export-pack-front-page',0,NULL,'exportInvoiceNo','Export / Invoice no.','text',true,false,NULL,ARRAY[]::text[],NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_1','dry-export-pack-front-page',0,NULL,'packingDate','Packing date','date',true,false,NULL,ARRAY[]::text[],NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_2','dry-export-pack-front-page',0,NULL,'noOfBoxesExported','No. of boxes exported','number',true,false,NULL,ARRAY[]::text[],NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_3','dry-export-pack-front-page',1,NULL,'labellingListAttached','REC 7.4.6 Dry Labelling List attached?','upload',true,false,NULL,ARRAY[]::text[],NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_4','dry-export-pack-front-page',1,NULL,'cmtLabellingList','Comments — REC 7.4.6 Dry Labelling List','text',false,false,NULL,ARRAY[]::text[],NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_5','dry-export-pack-front-page',1,NULL,'rec747Attached','REC 7.4.7 Labelling of Dry Boxes attached?','recordpick',true,false,NULL,ARRAY[]::text[],NULL,5,NULL,NULL,NULL,NULL,NULL,NULL,'{"sourceRecordKey": "labelling-of-dry-boxes"}'::jsonb);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_6','dry-export-pack-front-page',1,NULL,'cmt747','Comments — REC 7.4.7 Labelling of Dry Boxes','text',false,false,NULL,ARRAY[]::text[],NULL,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_7','dry-export-pack-front-page',1,NULL,'rec749Attached','REC 7.4.9 Dry Stock Transfers attached?','recordpick',true,false,NULL,ARRAY[]::text[],NULL,7,NULL,NULL,NULL,NULL,NULL,NULL,'{"sourceRecordKey": "dry-stock-transfers"}'::jsonb);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_8','dry-export-pack-front-page',1,NULL,'cmt749','Comments — REC 7.4.9 Dry Stock Transfers','text',false,false,NULL,ARRAY[]::text[],NULL,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_9','dry-export-pack-front-page',1,NULL,'signedPackingListsAttached','Signed packing lists attached?','upload',true,false,NULL,ARRAY[]::text[],NULL,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_10','dry-export-pack-front-page',1,NULL,'cmtPackingLists','Comments — Signed packing lists','text',false,false,NULL,ARRAY[]::text[],NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_11','dry-export-pack-front-page',1,NULL,'healthCertificatesAttached','Health certificates attached?','upload',true,false,NULL,ARRAY[]::text[],NULL,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dep2_fld_12','dry-export-pack-front-page',1,NULL,'cmtHealthCerts','Comments — Health certificates','text',false,false,NULL,ARRAY[]::text[],NULL,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
COMMIT;

-- Check: should return 2 sections and 13 fields
SELECT (SELECT count(*) FROM "RecordSectionDef" WHERE "recordKey"='dry-export-pack-front-page') sections,(SELECT count(*) FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page') fields;
