-- Dry Export Pack Front Page: add Comments fields and make the six record pickers optional.
-- Additive: nothing else on this record is changed. Safe to re-run.
BEGIN;
DELETE FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page' AND "key" IN ('cmt745','cmt746','cmt747','cmt748','cmt749','cmt7410');
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") SELECT 'dep_cmt_0','dry-export-pack-front-page',"sectionIndex",NULL,'cmt745','Comments — REC 7.4.5 Boxing & Labelling','text',false,false,NULL,ARRAY[]::text[],NULL,300,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page' AND "key"='rec745Attached';
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") SELECT 'dep_cmt_1','dry-export-pack-front-page',"sectionIndex",NULL,'cmt746','Comments — REC 7.4.6 Dry Stock Control','text',false,false,NULL,ARRAY[]::text[],NULL,301,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page' AND "key"='rec745Attached';
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") SELECT 'dep_cmt_2','dry-export-pack-front-page',"sectionIndex",NULL,'cmt747','Comments — REC 7.4.7 Labelling of Dry Boxes','text',false,false,NULL,ARRAY[]::text[],NULL,302,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page' AND "key"='rec745Attached';
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") SELECT 'dep_cmt_3','dry-export-pack-front-page',"sectionIndex",NULL,'cmt748','Comments — REC 7.4.8 Dry Labelling List','text',false,false,NULL,ARRAY[]::text[],NULL,303,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page' AND "key"='rec745Attached';
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") SELECT 'dep_cmt_4','dry-export-pack-front-page',"sectionIndex",NULL,'cmt749','Comments — REC 7.4.9 Dry Stock Transfers','text',false,false,NULL,ARRAY[]::text[],NULL,304,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page' AND "key"='rec745Attached';
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") SELECT 'dep_cmt_5','dry-export-pack-front-page',"sectionIndex",NULL,'cmt7410','Comments — REC 7.4.10 Dried Abalone Transfer','text',false,false,NULL,ARRAY[]::text[],NULL,305,NULL,NULL,NULL,NULL,NULL,NULL,NULL FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page' AND "key"='rec745Attached';
UPDATE "RecordFieldDef" SET "required"=false WHERE "recordKey"='dry-export-pack-front-page' AND "key" IN ('rec745Attached','rec746Attached','rec747Attached','rec748Attached','rec749Attached','rec7410Attached');
UPDATE "RecordDefinition" SET "version"="version"+1,"updatedAt"=now() WHERE "recordKey"='dry-export-pack-front-page';
COMMIT;

-- Check: should list 6 cmt fields (required=false) and the six rec74x pickers with required=false
SELECT "key","required","sectionIndex","position" FROM "RecordFieldDef" WHERE "recordKey"='dry-export-pack-front-page' ORDER BY "position";
