-- Update ONLY the Dry NRCS Packs definition (attachments checklist). Safe to re-run.
BEGIN;
DELETE FROM "RecordFieldDef" WHERE "recordKey"='dry-nrcs-packs';
DELETE FROM "RecordSectionDef" WHERE "recordKey"='dry-nrcs-packs';
DELETE FROM "RecordAutofillDef" WHERE "recordKey"='dry-nrcs-packs';
UPDATE "RecordDefinition" SET "engine"='form-record',"mount"='#frRoot',"pageFile"='Production-Information-NRCS-(Dry)-dry-nrcs-packs.html',"docCode"='Production Information NRCS (Dry)',"title"='Dry NRCS Packs — Production Information NRCS',"docRevisionStart"=1,"jobInfoGroup"=NULL,"clientHook"=NULL,"primaryBatchField"=NULL,"extraBatchFields"=ARRAY[]::text[],"extraJson"='{"listColumns":["jobNumberProductionDate","nrcsAgCode"]}'::jsonb,"version"="version"+1,"updatedAt"=now() WHERE "recordKey"='dry-nrcs-packs';
INSERT INTO "RecordSectionDef" ("id","recordKey","title","kind","position","extraJson") VALUES ('dnp_sec_0','dry-nrcs-packs','Batch details','fields',0,NULL);
INSERT INTO "RecordSectionDef" ("id","recordKey","title","kind","position","extraJson") VALUES ('dnp_sec_1','dry-nrcs-packs','Attachments checklist','roster',1,'{"collapseRows":false,"defaultRows":[{"recordName":"REC 7.1.2 Abalone Receiving"},{"recordName":"REC 7.1.1 Basket Removal / Shucking / Gutting"},{"recordName":"REC 7.1.3 Bleeding & Salting Checklist"},{"recordName":"REC 7.1.4 Washing Control Sheet"},{"recordName":"REC 7.8.1 Dry Chiller Batch Control"},{"recordName":"REC 7.4.0 Dry Cooking"},{"recordName":"REC 7.4.2 Dry Monitoring"},{"recordName":"REC 7.4.3.1 Grading Production Log (Cultivated)"},{"recordName":"REC 7.4.3.2 Grading Production Log (Ranched)"}]}'::jsonb);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_0','dry-nrcs-packs',0,NULL,'jobNo','Job number','jobsearch',false,false,NULL,ARRAY[]::text[],NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,'{"route":"Dried"}'::jsonb);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_1','dry-nrcs-packs',0,NULL,'receivingDate','Receiving date','date',true,false,NULL,ARRAY[]::text[],NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_2','dry-nrcs-packs',0,NULL,'dateOfInspection','Date of inspection','date',false,false,NULL,ARRAY[]::text[],NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_3','dry-nrcs-packs',0,NULL,'jobNumberProductionDate','Job number / production date','text',false,false,NULL,ARRAY[]::text[],NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_4','dry-nrcs-packs',0,NULL,'nrcsAgCode','NRCS AG code','text',false,false,NULL,ARRAY[]::text[],NULL,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_5','dry-nrcs-packs',0,NULL,'productDescription','Product description','text',false,false,NULL,ARRAY[]::text[],NULL,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_6','dry-nrcs-packs',1,'@roster','recordName','Record','text',false,false,NULL,ARRAY[]::text[],NULL,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_7','dry-nrcs-packs',1,'@roster','attached','Attached','select',false,false,NULL,ARRAY['Yes','No']::text[],NULL,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordFieldDef" ("id","recordKey","sectionIndex","parentFieldKey","key","label","type","required","readOnly","unit","options","group","position","computeFn","computeArgs","recordPickSource","linkField","linkRelation","validateJson","extraJson") VALUES ('dnp_fld_8','dry-nrcs-packs',1,'@roster','comments','Comments','text',false,false,NULL,ARRAY[]::text[],NULL,10,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RecordAutofillDef" ("id","recordKey","watchKey","sourceRecordKey","matchField","fillMap","extraJson") VALUES ('dnp_af_0','dry-nrcs-packs','jobNo','abalone-receiving','jobNo','{"receivingDate":"receivingDate"}'::jsonb,NULL);
COMMIT;

-- Check: should return 1 definition, 2 sections, 9 fields, 1 autofill
SELECT (SELECT count(*) FROM "RecordSectionDef" WHERE "recordKey"='dry-nrcs-packs') sections,(SELECT count(*) FROM "RecordFieldDef" WHERE "recordKey"='dry-nrcs-packs') fields,(SELECT count(*) FROM "RecordAutofillDef" WHERE "recordKey"='dry-nrcs-packs') autofills;
