-- Index the columns the submission tables are actually looked up by (2026-09-21): each record's
-- top-level link fields (RecordFieldDef.linkField) -- job number on 46 tables plus the ingredient /
-- batch-code fields. 67 indexes on 50 tables. Generated by
--   node scripts/generate-submission-schema.mjs --index-sql
-- Dates and submittedAt are deliberately not indexed: nothing queries them per record, and the
-- store rewrites a record's whole table on every save, so each index is a write cost.
-- Purely additive.

CREATE INDEX "sub_dry_export_pack_front_page_jobNumber_idx" ON "sub_dry_export_pack_front_page"("jobNumber");
CREATE INDEX "sub_production_information_nrcs_jobNo_idx" ON "sub_production_information_nrcs"("jobNo");
CREATE INDEX "sub_cans_released_form_agCode_idx" ON "sub_cans_released_form"("agCode");
CREATE INDEX "sub_gonad_inspection_report_jobNo_idx" ON "sub_gonad_inspection_report"("jobNo");
CREATE INDEX "sub_incubator_cans_log_jobNo_idx" ON "sub_incubator_cans_log"("jobNo");
CREATE INDEX "sub_basket_removal_shucking_gutting_jobNo_idx" ON "sub_basket_removal_shucking_gutting"("jobNo");
CREATE INDEX "sub_abalone_receiving_jobNo_idx" ON "sub_abalone_receiving"("jobNo");
CREATE INDEX "sub_salting_and_tumbling_jobNo_idx" ON "sub_salting_and_tumbling"("jobNo");
CREATE INDEX "sub_bleeding_and_salting_jobNo_idx" ON "sub_bleeding_and_salting"("jobNo");
CREATE INDEX "sub_bleeding_and_salting_saltBatchCode_idx" ON "sub_bleeding_and_salting"("saltBatchCode");
CREATE INDEX "sub_bleeding_and_salting_bakingSodaBatchCode_idx" ON "sub_bleeding_and_salting"("bakingSodaBatchCode");
CREATE INDEX "sub_washing_control_sheet_jobNo_idx" ON "sub_washing_control_sheet"("jobNo");
CREATE INDEX "sub_salting_oosw_jobNo_idx" ON "sub_salting_oosw"("jobNo");
CREATE INDEX "sub_scrubbing_check_supervisor_jobNo_idx" ON "sub_scrubbing_check_supervisor"("jobNo");
CREATE INDEX "sub_stock_loading_jobNo_idx" ON "sub_stock_loading"("jobNo");
CREATE INDEX "sub_qc_report_jobNumber_idx" ON "sub_qc_report"("jobNumber");
CREATE INDEX "sub_double_seam_inspection_report_jobNo_idx" ON "sub_double_seam_inspection_report"("jobNo");
CREATE INDEX "sub_rework_log_jobNo_idx" ON "sub_rework_log"("jobNo");
CREATE INDEX "sub_stock_transfers_jobNo_idx" ON "sub_stock_transfers"("jobNo");
CREATE INDEX "sub_scrubbing_checklist_qc_jobNo_idx" ON "sub_scrubbing_checklist_qc"("jobNo");
CREATE INDEX "sub_precooking_check_sheet_jobNumber_idx" ON "sub_precooking_check_sheet"("jobNumber");
CREATE INDEX "sub_abalone_packing_specification_jobNo_idx" ON "sub_abalone_packing_specification"("jobNo");
CREATE INDEX "sub_can_filling_and_printing_jobNo_idx" ON "sub_can_filling_and_printing"("jobNo");
CREATE INDEX "sub_cans_produced_jobNumber_idx" ON "sub_cans_produced"("jobNumber");
CREATE INDEX "sub_retorting_control_sheet_jobNumber_idx" ON "sub_retorting_control_sheet"("jobNumber");
CREATE INDEX "sub_retort_inspection_report_jobNo_idx" ON "sub_retort_inspection_report"("jobNo");
CREATE INDEX "sub_ingredient_weighing_jobNo_idx" ON "sub_ingredient_weighing"("jobNo");
CREATE INDEX "sub_ingredient_weighing_chickenFlavourBatchCode_idx" ON "sub_ingredient_weighing"("chickenFlavourBatchCode");
CREATE INDEX "sub_ingredient_weighing_vegetableBaseBatchCode_idx" ON "sub_ingredient_weighing"("vegetableBaseBatchCode");
CREATE INDEX "sub_ingredient_weighing_gelatineBatchCode_idx" ON "sub_ingredient_weighing"("gelatineBatchCode");
CREATE INDEX "sub_ingredient_weighing_xanthanGumBatchCode_idx" ON "sub_ingredient_weighing"("xanthanGumBatchCode");
CREATE INDEX "sub_ingredient_weighing_maltSugarBatchCode_idx" ON "sub_ingredient_weighing"("maltSugarBatchCode");
CREATE INDEX "sub_ingredient_weighing_tapiocaStarchBatchCode_idx" ON "sub_ingredient_weighing"("tapiocaStarchBatchCode");
CREATE INDEX "sub_ingredient_weighing_brownSugarBatchCode_idx" ON "sub_ingredient_weighing"("brownSugarBatchCode");
CREATE INDEX "sub_ingredient_weighing_sherloneSauceBatchCode_idx" ON "sub_ingredient_weighing"("sherloneSauceBatchCode");
CREATE INDEX "sub_sauce_mixing_jobNo_idx" ON "sub_sauce_mixing"("jobNo");
CREATE INDEX "sub_sauce_mixing_brothBatchDate_idx" ON "sub_sauce_mixing"("brothBatchDate");
CREATE INDEX "sub_sauce_mixing_chickenLiquidBatchCode_idx" ON "sub_sauce_mixing"("chickenLiquidBatchCode");
CREATE INDEX "sub_sauce_mixing_smokeyFlavourBatchCode_idx" ON "sub_sauce_mixing"("smokeyFlavourBatchCode");
CREATE INDEX "sub_sauce_mixing_cvgMixBatchCode_idx" ON "sub_sauce_mixing"("cvgMixBatchCode");
CREATE INDEX "sub_sauce_mixing_mdMixBatchCode_idx" ON "sub_sauce_mixing"("mdMixBatchCode");
CREATE INDEX "sub_sauce_mixing_tsMixBatchCode_idx" ON "sub_sauce_mixing"("tsMixBatchCode");
CREATE INDEX "sub_sauce_mixing_soMixBatchCode_idx" ON "sub_sauce_mixing"("soMixBatchCode");
CREATE INDEX "sub_brine_mixing_report_jobNumber_idx" ON "sub_brine_mixing_report"("jobNumber");
CREATE INDEX "sub_dry_cooking_jobNumber_idx" ON "sub_dry_cooking"("jobNumber");
CREATE INDEX "sub_drying_process_jobNumber_idx" ON "sub_drying_process"("jobNumber");
CREATE INDEX "sub_dried_abalone_transfer_jobNumber_idx" ON "sub_dried_abalone_transfer"("jobNumber");
CREATE INDEX "sub_dry_monitoring_jobNumber_idx" ON "sub_dry_monitoring"("jobNumber");
CREATE INDEX "sub_grading_production_log_cultivated_jobNumber_idx" ON "sub_grading_production_log_cultivated"("jobNumber");
CREATE INDEX "sub_grading_production_log_ranched_jobNumber_idx" ON "sub_grading_production_log_ranched"("jobNumber");
CREATE INDEX "sub_grading_boxing_traceability_jobNo_idx" ON "sub_grading_boxing_traceability"("jobNo");
CREATE INDEX "sub_dry_stock_control_jobNo_idx" ON "sub_dry_stock_control"("jobNo");
CREATE INDEX "sub_live_production_pack_jobNumber_idx" ON "sub_live_production_pack"("jobNumber");
CREATE INDEX "sub_chemical_stock_issue_register_batchNumber_idx" ON "sub_chemical_stock_issue_register"("batchNumber");
CREATE INDEX "sub_salt_issuing_register_batchNumber_idx" ON "sub_salt_issuing_register"("batchNumber");
CREATE INDEX "sub_chiller_batch_control_jobNo_idx" ON "sub_chiller_batch_control"("jobNo");
CREATE INDEX "sub_dry_chiller_batch_control_jobNo_idx" ON "sub_dry_chiller_batch_control"("jobNo");
CREATE INDEX "sub_seamer_inspection_report_jobNo_idx" ON "sub_seamer_inspection_report"("jobNo");
CREATE INDEX "sub_cans_incoming_inspection_jobNo_idx" ON "sub_cans_incoming_inspection"("jobNo");
CREATE INDEX "sub_dispatch_loading_inspection_checklist_jobNo_idx" ON "sub_dispatch_loading_inspection_checklist"("jobNo");
CREATE INDEX "sub_dispatch_receiving_checklist_jobNumber_idx" ON "sub_dispatch_receiving_checklist"("jobNumber");
CREATE INDEX "sub_chiller_temperature_monitoring_jobNo_idx" ON "sub_chiller_temperature_monitoring"("jobNo");
CREATE INDEX "sub_disposition_investigation_record_productionCode_idx" ON "sub_disposition_investigation_record"("productionCode");
CREATE INDEX "sub_traceability_mock_recall_canned_braised_abalone_jobNo_idx" ON "sub_traceability_mock_recall_canned_braised_abalone"("jobNo");
CREATE INDEX "sub_traceability_mock_recall_canned_abalone_jobNo_idx" ON "sub_traceability_mock_recall_canned_abalone"("jobNo");
CREATE INDEX "sub_traceability_mock_recall_canned_minced_abalone_jobNo_idx" ON "sub_traceability_mock_recall_canned_minced_abalone"("jobNo");
CREATE INDEX "sub_traceability_mock_recall_dried_abalone_jobNo_idx" ON "sub_traceability_mock_recall_dried_abalone"("jobNo");
